-- Huddle profile and direct-network persistence.
-- Run this once in the Supabase SQL editor before testing the cloud-backed services.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  tag text not null default '',
  phone_number text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.network_members (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  member_id uuid references public.profiles(id) on delete set null,
  member_tag text,
  member_phone_number text,
  created_at timestamptz not null default now(),
  constraint network_members_has_reference check (
    member_id is not null or member_tag is not null or member_phone_number is not null
  )
);

create unique index if not exists network_members_owner_member_key
  on public.network_members(owner_id, member_id)
  where member_id is not null;

create unique index if not exists network_members_owner_tag_key
  on public.network_members(owner_id, member_tag)
  where member_tag is not null;

create unique index if not exists network_members_owner_phone_key
  on public.network_members(owner_id, member_phone_number)
  where member_phone_number is not null;

alter table public.profiles enable row level security;
alter table public.network_members enable row level security;

create policy "Authenticated users can read profiles"
  on public.profiles for select
  to authenticated
  using (true);

create policy "Users can create their own profile"
  on public.profiles for insert
  to authenticated
  with check (auth.uid() = id);

create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Users can read their network"
  on public.network_members for select
  to authenticated
  using (auth.uid() = owner_id);

create policy "Users can add to their network"
  on public.network_members for insert
  to authenticated
  with check (auth.uid() = owner_id);

create policy "Users can remove from their network"
  on public.network_members for delete
  to authenticated
  using (auth.uid() = owner_id);

create table if not exists public.huddles (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  auto_archive_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.huddle_members (
  id bigint generated by default as identity primary key,
  huddle_id uuid not null references public.huddles(id) on delete cascade,
  member_id uuid references public.profiles(id) on delete set null,
  member_tag text,
  member_phone_number text,
  created_at timestamptz not null default now(),
  constraint huddle_members_has_reference check (
    member_id is not null or member_tag is not null or member_phone_number is not null
  )
);

create unique index if not exists huddle_members_huddle_member_key
  on public.huddle_members(huddle_id, member_id)
  where member_id is not null;

create unique index if not exists huddle_members_huddle_tag_key
  on public.huddle_members(huddle_id, member_tag)
  where member_tag is not null;

create unique index if not exists huddle_members_huddle_phone_key
  on public.huddle_members(huddle_id, member_phone_number)
  where member_phone_number is not null;

create or replace function public.can_access_huddle(target_huddle_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.huddles h
    where h.id = target_huddle_id
      and (
        h.owner_id = auth.uid()
        or exists (
          select 1
          from public.huddle_members hm
          left join public.profiles current_user_profile on current_user_profile.id = auth.uid()
          where hm.huddle_id = h.id
            and (
              hm.member_id = auth.uid()
              or hm.member_tag = current_user_profile.tag
              or hm.member_phone_number = current_user_profile.phone_number
            )
        )
      )
  );
$$;

create or replace function public.list_visible_huddles()
returns table (
  id uuid,
  title text,
  owner_id uuid,
  owner_tag text,
  owner_phone_number text,
  created_at timestamptz,
  auto_archive_at timestamptz,
  member_ids text[]
)
language sql
stable
security definer
set search_path = public
as $$
  select
    h.id,
    h.title,
    h.owner_id,
    owner_profile.tag,
    owner_profile.phone_number,
    h.created_at,
    h.auto_archive_at,
    coalesce(
      array_agg(
        coalesce(hm.member_id::text, hm.member_tag, hm.member_phone_number)
        order by hm.created_at
      ) filter (where hm.id is not null),
      '{}'::text[]
    )
  from public.huddles h
  join public.profiles owner_profile on owner_profile.id = h.owner_id
  left join public.huddle_members hm on hm.huddle_id = h.id
  where public.can_access_huddle(h.id)
  group by h.id, owner_profile.tag, owner_profile.phone_number;
$$;

create or replace function public.create_huddle(
  p_title text,
  p_auto_archive_at timestamptz,
  p_members jsonb
)
returns table (
  id uuid,
  title text,
  owner_id uuid,
  created_at timestamptz,
  auto_archive_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  new_huddle public.huddles;
begin
  if auth.uid() is null then
    raise exception 'An authenticated account is required.';
  end if;

  if coalesce(trim(p_title), '') = '' then
    raise exception 'Huddle title is required.';
  end if;

  if jsonb_array_length(coalesce(p_members, '[]'::jsonb)) = 0 then
    raise exception 'At least one huddle member is required.';
  end if;

  insert into public.huddles (owner_id, title, auto_archive_at)
  values (auth.uid(), trim(p_title), p_auto_archive_at)
  returning * into new_huddle;

  insert into public.huddle_members (
    huddle_id,
    member_id,
    member_tag,
    member_phone_number
  )
  select
    new_huddle.id,
    nullif(member.value ->> 'member_id', '')::uuid,
    nullif(member.value ->> 'member_tag', ''),
    nullif(member.value ->> 'member_phone_number', '')
  from jsonb_array_elements(p_members) as member(value);

  return query
  select
    new_huddle.id,
    new_huddle.title,
    new_huddle.owner_id,
    new_huddle.created_at,
    new_huddle.auto_archive_at;
end;
$$;

grant execute on function public.create_huddle(text, timestamptz, jsonb) to authenticated;

alter table public.huddles enable row level security;
alter table public.huddle_members enable row level security;

drop policy if exists "Members can read visible huddles" on public.huddles;
drop policy if exists "Authenticated users can create huddles" on public.huddles;
drop policy if exists "Members can update visible huddles" on public.huddles;
drop policy if exists "Members can delete visible huddles" on public.huddles;
drop policy if exists "Members can read visible huddle members" on public.huddle_members;
drop policy if exists "Huddle members can be added to visible huddles" on public.huddle_members;
drop policy if exists "Huddle members can be removed from visible huddles" on public.huddle_members;

create policy "Members can read visible huddles"
  on public.huddles for select
  to authenticated
  using (public.can_access_huddle(id));

create policy "Authenticated users can create huddles"
  on public.huddles for insert
  to authenticated
  with check (auth.uid() = owner_id);

create policy "Members can update visible huddles"
  on public.huddles for update
  to authenticated
  using (public.can_access_huddle(id))
  with check (public.can_access_huddle(id));

create policy "Members can delete visible huddles"
  on public.huddles for delete
  to authenticated
  using (public.can_access_huddle(id));

create policy "Members can read visible huddle members"
  on public.huddle_members for select
  to authenticated
  using (public.can_access_huddle(huddle_id));

create policy "Huddle members can be added to visible huddles"
  on public.huddle_members for insert
  to authenticated
  with check (public.can_access_huddle(huddle_id));

create policy "Huddle members can be removed from visible huddles"
  on public.huddle_members for delete
  to authenticated
  using (public.can_access_huddle(huddle_id));
