-- Huddle profile and direct-network persistence.
-- Run this once in the Supabase SQL editor before testing the cloud-backed services.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  tag text not null default '',
  phone_number text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.network_members (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  member_id uuid references public.profiles(id) on delete set null,
  member_tag text,
  member_phone_number text,
  created_at timestamptz not null default now(),
  constraint network_members_has_reference check (
    member_id is not null or member_tag is not null or member_phone_number is not null
  )
);

create unique index if not exists network_members_owner_member_key
  on public.network_members(owner_id, member_id)
  where member_id is not null;

create unique index if not exists network_members_owner_tag_key
  on public.network_members(owner_id, member_tag)
  where member_tag is not null;

create unique index if not exists network_members_owner_phone_key
  on public.network_members(owner_id, member_phone_number)
  where member_phone_number is not null;

alter table public.profiles enable row level security;
alter table public.network_members enable row level security;

-- PostgreSQL does not support CREATE POLICY IF NOT EXISTS. Recreate named
-- policies so this schema remains safe to rerun and policy changes apply.
drop policy if exists "Authenticated users can read profiles" on public.profiles;
drop policy if exists "Users can create their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;
drop policy if exists "Users can read their network" on public.network_members;
drop policy if exists "Users can add to their network" on public.network_members;
drop policy if exists "Users can remove from their network" on public.network_members;

create policy "Authenticated users can read profiles"
  on public.profiles for select
  to authenticated
  using (true);

create policy "Users can create their own profile"
  on public.profiles for insert
  to authenticated
  with check (auth.uid() = id);

create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Users can read their network"
  on public.network_members for select
  to authenticated
  using (auth.uid() = owner_id);

create policy "Users can add to their network"
  on public.network_members for insert
  to authenticated
  with check (auth.uid() = owner_id);

create policy "Users can remove from their network"
  on public.network_members for delete
  to authenticated
  using (auth.uid() = owner_id);

create table if not exists public.huddles (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  auto_archive_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.huddle_members (
  id bigint generated by default as identity primary key,
  huddle_id uuid not null references public.huddles(id) on delete cascade,
  member_id uuid references public.profiles(id) on delete set null,
  member_tag text,
  member_phone_number text,
  created_at timestamptz not null default now(),
  constraint huddle_members_has_reference check (
    member_id is not null or member_tag is not null or member_phone_number is not null
  )
);

create unique index if not exists huddle_members_huddle_member_key
  on public.huddle_members(huddle_id, member_id)
  where member_id is not null;

create unique index if not exists huddle_members_huddle_tag_key
  on public.huddle_members(huddle_id, member_tag)
  where member_tag is not null;

create unique index if not exists huddle_members_huddle_phone_key
  on public.huddle_members(huddle_id, member_phone_number)
  where member_phone_number is not null;

create or replace function public.can_access_huddle(target_huddle_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.huddles h
    where h.id = target_huddle_id
      and exists (
        select 1
        from public.huddle_members hm
        left join public.profiles current_user_profile on current_user_profile.id = auth.uid()
        where hm.huddle_id = h.id
          and (
            hm.member_id = auth.uid()
            or hm.member_tag = current_user_profile.tag
            or hm.member_phone_number = current_user_profile.phone_number
          )
      )
  );
$$;

create or replace function public.list_visible_huddles()
returns table (
  id uuid,
  title text,
  owner_id uuid,
  owner_tag text,
  owner_phone_number text,
  created_at timestamptz,
  auto_archive_at timestamptz,
  member_ids text[]
)
language sql
stable
security definer
set search_path = public
as $$
  select
    h.id,
    h.title,
    h.owner_id,
    owner_profile.tag,
    owner_profile.phone_number,
    h.created_at,
    h.auto_archive_at,
    coalesce(
      array_agg(
        coalesce(hm.member_id::text, hm.member_tag, hm.member_phone_number)
        order by hm.created_at
      ) filter (where hm.id is not null),
      '{}'::text[]
    )
  from public.huddles h
  join public.profiles owner_profile on owner_profile.id = h.owner_id
  left join public.huddle_members hm on hm.huddle_id = h.id
  where public.can_access_huddle(h.id)
  group by h.id, owner_profile.tag, owner_profile.phone_number;
$$;

create or replace function public.sync_current_user_huddle_network()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_profile public.profiles;
begin
  if auth.uid() is null then
    return;
  end if;

  select *
  into current_profile
  from public.profiles
  where id = auth.uid();

  if not found then
    return;
  end if;

  with shared_huddles as (
    select h.id
    from public.huddles h
    where exists (
        select 1
        from public.huddle_members hm
        where hm.huddle_id = h.id
          and (
            hm.member_id = current_profile.id
            or (
              current_profile.tag <> ''
              and hm.member_tag = current_profile.tag
            )
            or (
              current_profile.phone_number <> ''
              and hm.member_phone_number = current_profile.phone_number
            )
          )
      )
  ),
  candidate_members as (
    select
      coalesce(resolved_member.id, hm.member_id),
      case
        when resolved_member.id is null and hm.member_id is null then hm.member_tag
        else null
      end,
      case
        when resolved_member.id is null and hm.member_id is null then hm.member_phone_number
        else null
      end
    from shared_huddles h
    join public.huddle_members hm on hm.huddle_id = h.id
    left join public.profiles resolved_member on (
      resolved_member.id = hm.member_id
      or (
        hm.member_tag is not null
        and hm.member_tag <> ''
        and resolved_member.tag = hm.member_tag
      )
      or (
        hm.member_phone_number is not null
        and hm.member_phone_number <> ''
        and resolved_member.phone_number = hm.member_phone_number
      )
    )
  )
  insert into public.network_members (
    owner_id,
    member_id,
    member_tag,
    member_phone_number
  )
  select
    current_profile.id,
    candidate.member_id,
    candidate.member_tag,
    candidate.member_phone_number
  from candidate_members candidate
  where (candidate.member_id is not null
      or candidate.member_tag is not null
      or candidate.member_phone_number is not null)
    and (
      candidate.member_id is null
      or candidate.member_id <> current_profile.id
    )
    and (
      candidate.member_tag is null
      or candidate.member_tag <> current_profile.tag
    )
    and (
      candidate.member_phone_number is null
      or candidate.member_phone_number <> current_profile.phone_number
    )
  on conflict do nothing;
end;
$$;

grant execute on function public.sync_current_user_huddle_network() to authenticated;

create or replace function public.create_huddle(
  p_title text,
  p_auto_archive_at timestamptz,
  p_members jsonb
)
returns table (
  id uuid,
  title text,
  owner_id uuid,
  created_at timestamptz,
  auto_archive_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  new_huddle public.huddles;
begin
  if auth.uid() is null then
    raise exception 'An authenticated account is required.';
  end if;

  if coalesce(trim(p_title), '') = '' then
    raise exception 'Huddle title is required.';
  end if;

  if jsonb_array_length(coalesce(p_members, '[]'::jsonb)) = 0 then
    raise exception 'At least one huddle member is required.';
  end if;

  insert into public.huddles (owner_id, title, auto_archive_at)
  values (auth.uid(), trim(p_title), p_auto_archive_at)
  returning * into new_huddle;

  insert into public.huddle_members (
    huddle_id,
    member_id,
    member_tag,
    member_phone_number
  )
  values (new_huddle.id, auth.uid(), null, null)
  on conflict do nothing;

  insert into public.huddle_members (
    huddle_id,
    member_id,
    member_tag,
    member_phone_number
  )
  select
    new_huddle.id,
    nullif(member.value ->> 'member_id', '')::uuid,
    nullif(member.value ->> 'member_tag', ''),
    nullif(member.value ->> 'member_phone_number', '')
  from jsonb_array_elements(p_members) as member(value)
  on conflict do nothing;

  return query
  select
    new_huddle.id,
    new_huddle.title,
    new_huddle.owner_id,
    new_huddle.created_at,
    new_huddle.auto_archive_at;
end;
$$;

grant execute on function public.create_huddle(text, timestamptz, jsonb) to authenticated;

create or replace function public.update_huddle(
  p_huddle_id uuid,
  p_title text,
  p_auto_archive_at timestamptz,
  p_members jsonb
)
returns table (
  id uuid,
  title text,
  owner_id uuid,
  created_at timestamptz,
  auto_archive_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_huddle public.huddles;
begin
  if auth.uid() is null then
    raise exception 'An authenticated account is required.';
  end if;

  select *
  into existing_huddle
  from public.huddles
  where id = p_huddle_id;

  if not found then
    raise exception 'Huddle could not be found.';
  end if;

  if not public.can_access_huddle(p_huddle_id) then
    raise exception 'You are not allowed to update this huddle.';
  end if;

  if coalesce(trim(p_title), '') = '' then
    raise exception 'Huddle title is required.';
  end if;

  if jsonb_array_length(coalesce(p_members, '[]'::jsonb)) = 0 then
    raise exception 'At least one huddle member is required.';
  end if;

  update public.huddles
  set title = trim(p_title), auto_archive_at = p_auto_archive_at
  where id = p_huddle_id;

  delete from public.huddle_members
  where huddle_id = p_huddle_id;

  insert into public.huddle_members (
    huddle_id,
    member_id,
    member_tag,
    member_phone_number
  )
  select
    p_huddle_id,
    nullif(member.value ->> 'member_id', '')::uuid,
    nullif(member.value ->> 'member_tag', ''),
    nullif(member.value ->> 'member_phone_number', '')
  from jsonb_array_elements(p_members) as member(value)
  on conflict do nothing;

  return query
  select
    h.id,
    h.title,
    h.owner_id,
    h.created_at,
    h.auto_archive_at
  from public.huddles h
  where h.id = p_huddle_id;
end;
$$;

grant execute on function public.update_huddle(uuid, text, timestamptz, jsonb) to authenticated;

alter table public.huddles enable row level security;
alter table public.huddle_members enable row level security;

drop policy if exists "Members can read visible huddles" on public.huddles;
drop policy if exists "Authenticated users can create huddles" on public.huddles;
drop policy if exists "Members can update visible huddles" on public.huddles;
drop policy if exists "Members can delete visible huddles" on public.huddles;
drop policy if exists "Members can read visible huddle members" on public.huddle_members;
drop policy if exists "Huddle members can be added to visible huddles" on public.huddle_members;
drop policy if exists "Huddle members can be removed from visible huddles" on public.huddle_members;

create policy "Members can read visible huddles"
  on public.huddles for select
  to authenticated
  using (public.can_access_huddle(id));

create policy "Authenticated users can create huddles"
  on public.huddles for insert
  to authenticated
  with check (auth.uid() = owner_id);

create policy "Members can update visible huddles"
  on public.huddles for update
  to authenticated
  using (public.can_access_huddle(id))
  with check (public.can_access_huddle(id));

create policy "Members can delete visible huddles"
  on public.huddles for delete
  to authenticated
  using (public.can_access_huddle(id));

create policy "Members can read visible huddle members"
  on public.huddle_members for select
  to authenticated
  using (public.can_access_huddle(huddle_id));

create policy "Huddle members can be added to visible huddles"
  on public.huddle_members for insert
  to authenticated
  with check (public.can_access_huddle(huddle_id));

create policy "Huddle members can be removed from visible huddles"
  on public.huddle_members for delete
  to authenticated
  using (public.can_access_huddle(huddle_id));
