-- Huddle profile and direct-network persistence.
-- Run this once in the Supabase SQL editor before testing the cloud-backed services.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  tag text not null default '',
  phone_number text not null default '',
  avatar_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists avatar_url text not null default '';

create table if not exists public.network_members (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  member_id uuid references public.profiles(id) on delete set null,
  member_tag text,
  member_phone_number text,
  status text not null default 'active',
  left_at timestamptz,
  created_at timestamptz not null default now(),
  constraint network_members_has_reference check (
    member_id is not null or member_tag is not null or member_phone_number is not null
  )
);

create unique index if not exists network_members_owner_member_key
  on public.network_members(owner_id, member_id)
  where member_id is not null;

create unique index if not exists network_members_owner_tag_key
  on public.network_members(owner_id, member_tag)
  where member_tag is not null;

create unique index if not exists network_members_owner_phone_key
  on public.network_members(owner_id, member_phone_number)
  where member_phone_number is not null;

alter table public.profiles enable row level security;
alter table public.network_members enable row level security;

-- PostgreSQL does not support CREATE POLICY IF NOT EXISTS. Recreate named
-- policies so this schema remains safe to rerun and policy changes apply.
drop policy if exists "Authenticated users can read profiles" on public.profiles;
drop policy if exists "Users can create their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;
drop policy if exists "Users can read their network" on public.network_members;
drop policy if exists "Users can add to their network" on public.network_members;
drop policy if exists "Users can remove from their network" on public.network_members;

create policy "Authenticated users can read profiles"
  on public.profiles for select
  to authenticated
  using (true);

create policy "Users can create their own profile"
  on public.profiles for insert
  to authenticated
  with check (auth.uid() = id);

create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Users can read their network"
  on public.network_members for select
  to authenticated
  using (auth.uid() = owner_id);

create policy "Users can add to their network"
  on public.network_members for insert
  to authenticated
  with check (auth.uid() = owner_id);

create policy "Users can remove from their network"
  on public.network_members for delete
  to authenticated
  using (auth.uid() = owner_id);

create table if not exists public.huddles (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  auto_archive_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.huddle_members (
  id bigint generated by default as identity primary key,
  huddle_id uuid not null references public.huddles(id) on delete cascade,
  member_id uuid references public.profiles(id) on delete set null,
  member_tag text,
  member_phone_number text,
  created_at timestamptz not null default now(),
  constraint huddle_members_has_reference check (
    member_id is not null or member_tag is not null or member_phone_number is not null
  ),
  constraint huddle_members_status_check check (status in ('active', 'left'))
);

alter table public.huddle_members
  add column if not exists status text not null default 'active';

alter table public.huddle_members
  add column if not exists left_at timestamptz;

alter table public.huddle_members
  drop constraint if exists huddle_members_status_check;

alter table public.huddle_members
  add constraint huddle_members_status_check check (status in ('active', 'left'));

create unique index if not exists huddle_members_huddle_member_key
  on public.huddle_members(huddle_id, member_id)
  where member_id is not null;

create unique index if not exists huddle_members_huddle_tag_key
  on public.huddle_members(huddle_id, member_tag)
  where member_tag is not null;

create unique index if not exists huddle_members_huddle_phone_key
  on public.huddle_members(huddle_id, member_phone_number)
  where member_phone_number is not null;

create table if not exists public.huddle_messages (
  id uuid primary key default gen_random_uuid(),
  huddle_id uuid not null references public.huddles(id) on delete cascade,
  body text not null check (length(trim(body)) > 0),
  kind text not null check (kind in ('user', 'system')),
  activity_type text check (
    activity_type is null
    or activity_type in ('auto_archive_updated', 'huddle_created', 'member_added', 'member_left', 'member_removed', 'title_updated')
  ),
  author_id uuid references public.profiles(id) on delete set null,
  author_name text not null,
  created_at timestamptz not null default now(),
  constraint huddle_messages_kind_matches_activity check (
    (kind = 'user' and activity_type is null)
    or (kind = 'system' and activity_type is not null)
  )
);

alter table public.huddle_messages
  drop constraint if exists huddle_messages_activity_type_check;

alter table public.huddle_messages
  add constraint huddle_messages_activity_type_check check (
    activity_type is null
    or activity_type in ('auto_archive_updated', 'huddle_created', 'member_added', 'member_left', 'member_removed', 'title_updated')
  );

create index if not exists huddle_messages_huddle_created_key
  on public.huddle_messages(huddle_id, created_at, id);

create table if not exists public.huddle_read_states (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  huddle_id uuid not null references public.huddles(id) on delete cascade,
  last_read_at timestamptz not null default now(),
  primary key (profile_id, huddle_id)
);

alter table public.huddles replica identity full;
alter table public.huddle_members replica identity full;
alter table public.huddle_messages replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'huddles'
  ) then
    alter publication supabase_realtime add table public.huddles;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'huddle_members'
  ) then
    alter publication supabase_realtime add table public.huddle_members;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'huddle_messages'
  ) then
    alter publication supabase_realtime add table public.huddle_messages;
  end if;
end;
$$;

create or replace function public.can_access_huddle(target_huddle_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.huddles h
    where h.id = target_huddle_id
      and exists (
        select 1
        from public.huddle_members hm
        left join public.profiles current_user_profile on current_user_profile.id = auth.uid()
        where hm.huddle_id = h.id
          and hm.status = 'active'
          and (
            hm.member_id = auth.uid()
            or hm.member_tag = current_user_profile.tag
            or hm.member_phone_number = current_user_profile.phone_number
          )
      )
  );
$$;

create or replace function public.get_huddle_member_display_name(
  p_member_id uuid,
  p_member_tag text,
  p_member_phone_number text
)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    nullif(profile.display_name, ''),
    nullif(profile.tag, ''),
    nullif(profile.phone_number, ''),
    nullif(p_member_tag, ''),
    nullif(p_member_phone_number, ''),
    'Unknown member'
  )
  from (select 1) as input
  left join public.profiles profile on (
    profile.id = p_member_id
    or (p_member_tag is not null and p_member_tag <> '' and profile.tag = p_member_tag)
    or (
      p_member_phone_number is not null
      and p_member_phone_number <> ''
      and profile.phone_number = p_member_phone_number
    )
  )
  limit 1;
$$;

-- Adding result columns changes the function's PostgreSQL row type, which
-- cannot be updated in place. No database object depends on this RPC.
drop function if exists public.list_visible_huddles();

create function public.list_visible_huddles()
returns table (
  id uuid,
  title text,
  owner_id uuid,
  owner_tag text,
  owner_phone_number text,
  created_at timestamptz,
  auto_archive_at timestamptz,
  member_ids text[],
  unread_count integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    h.id,
    h.title,
    h.owner_id,
    owner_profile.tag,
    owner_profile.phone_number,
    h.created_at,
    h.auto_archive_at,
    coalesce(
      array_agg(
        coalesce(hm.member_id::text, hm.member_tag, hm.member_phone_number)
        order by hm.created_at
      ) filter (where hm.id is not null),
      '{}'::text[]
    ),
    (
      select count(*)::integer
      from public.huddle_messages message
      left join public.huddle_read_states read_state on (
        read_state.huddle_id = h.id
        and read_state.profile_id = auth.uid()
      )
      where message.huddle_id = h.id
        and message.created_at > coalesce(read_state.last_read_at, '-infinity'::timestamptz)
        and message.author_id is distinct from auth.uid()
    )
  from public.huddles h
  join public.profiles owner_profile on owner_profile.id = h.owner_id
  left join public.huddle_members hm on hm.huddle_id = h.id and hm.status = 'active'
  where public.can_access_huddle(h.id)
  group by h.id, owner_profile.tag, owner_profile.phone_number;
$$;

create or replace function public.sync_current_user_huddle_network()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_profile public.profiles;
begin
  if auth.uid() is null then
    return;
  end if;

  select *
  into current_profile
  from public.profiles
  where id = auth.uid();

  if not found then
    return;
  end if;

  with shared_huddles as (
    select h.id
    from public.huddles h
    where exists (
        select 1
        from public.huddle_members hm
        where hm.huddle_id = h.id
          and hm.status = 'active'
          and (
            hm.member_id = current_profile.id
            or (
              current_profile.tag <> ''
              and hm.member_tag = current_profile.tag
            )
            or (
              current_profile.phone_number <> ''
              and hm.member_phone_number = current_profile.phone_number
            )
          )
      )
  ),
  candidate_members as (
    select
      coalesce(resolved_member.id, hm.member_id) as member_id,
      case
        when resolved_member.id is null and hm.member_id is null then hm.member_tag
        else null
      end as member_tag,
      case
        when resolved_member.id is null and hm.member_id is null then hm.member_phone_number
        else null
      end as member_phone_number
    from shared_huddles h
    join public.huddle_members hm on hm.huddle_id = h.id and hm.status = 'active'
    left join public.profiles resolved_member on (
      resolved_member.id = hm.member_id
      or (
        hm.member_tag is not null
        and hm.member_tag <> ''
        and resolved_member.tag = hm.member_tag
      )
      or (
        hm.member_phone_number is not null
        and hm.member_phone_number <> ''
        and resolved_member.phone_number = hm.member_phone_number
      )
    )
  )
  insert into public.network_members (
    owner_id,
    member_id,
    member_tag,
    member_phone_number
  )
  select
    current_profile.id,
    candidate.member_id,
    candidate.member_tag,
    candidate.member_phone_number
  from candidate_members candidate
  where (candidate.member_id is not null
      or candidate.member_tag is not null
      or candidate.member_phone_number is not null)
    and (
      candidate.member_id is null
      or candidate.member_id <> current_profile.id
    )
    and (
      candidate.member_tag is null
      or candidate.member_tag <> current_profile.tag
    )
    and (
      candidate.member_phone_number is null
      or candidate.member_phone_number <> current_profile.phone_number
    )
  on conflict do nothing;
end;
$$;

grant execute on function public.sync_current_user_huddle_network() to authenticated;

create or replace function public.create_huddle(
  p_title text,
  p_auto_archive_at timestamptz,
  p_members jsonb
)
returns table (
  id uuid,
  title text,
  owner_id uuid,
  created_at timestamptz,
  auto_archive_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  new_huddle public.huddles;
begin
  if auth.uid() is null then
    raise exception 'An authenticated account is required.';
  end if;

  if coalesce(trim(p_title), '') = '' then
    raise exception 'Huddle title is required.';
  end if;

  if jsonb_array_length(coalesce(p_members, '[]'::jsonb)) = 0 then
    raise exception 'At least one huddle member is required.';
  end if;

  insert into public.huddles (owner_id, title, auto_archive_at)
  values (auth.uid(), trim(p_title), p_auto_archive_at)
  returning * into new_huddle;

  insert into public.huddle_members (
    huddle_id,
    member_id,
    member_tag,
    member_phone_number
  )
  values (new_huddle.id, auth.uid(), null, null)
  on conflict do nothing;

  insert into public.huddle_members (
    huddle_id,
    member_id,
    member_tag,
    member_phone_number
  )
  select
    new_huddle.id,
    nullif(member.value ->> 'member_id', '')::uuid,
    nullif(member.value ->> 'member_tag', ''),
    nullif(member.value ->> 'member_phone_number', '')
  from jsonb_array_elements(p_members) as member(value)
  on conflict do nothing;

  insert into public.huddle_messages (
    huddle_id,
    body,
    kind,
    activity_type,
    author_id,
    author_name
  )
  values (new_huddle.id, 'Huddle created', 'system', 'huddle_created', auth.uid(), 'System');

  return query
  select
    new_huddle.id,
    new_huddle.title,
    new_huddle.owner_id,
    new_huddle.created_at,
    new_huddle.auto_archive_at;
end;
$$;

grant execute on function public.create_huddle(text, timestamptz, jsonb) to authenticated;

create or replace function public.update_huddle(
  p_huddle_id uuid,
  p_title text,
  p_auto_archive_at timestamptz,
  p_members jsonb
)
returns table (
  id uuid,
  title text,
  owner_id uuid,
  created_at timestamptz,
  auto_archive_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_huddle public.huddles;
begin
  if auth.uid() is null then
    raise exception 'An authenticated account is required.';
  end if;

  select *
  into existing_huddle
  from public.huddles as huddle
  where huddle.id = p_huddle_id;

  if not found then
    raise exception 'Huddle could not be found.';
  end if;

  if not public.can_access_huddle(p_huddle_id) then
    raise exception 'You are not allowed to update this huddle.';
  end if;

  if coalesce(trim(p_title), '') = '' then
    raise exception 'Huddle title is required.';
  end if;

  if jsonb_array_length(coalesce(p_members, '[]'::jsonb)) = 0 then
    raise exception 'At least one huddle member is required.';
  end if;

  if existing_huddle.title <> trim(p_title) then
    insert into public.huddle_messages (
      huddle_id,
      body,
      kind,
      activity_type,
      author_id,
      author_name
    )
    values (
      p_huddle_id,
      format('Title updated from "%s" to "%s"', existing_huddle.title, trim(p_title)),
      'system',
      'title_updated',
      auth.uid(),
      'System'
    );
  end if;

  if existing_huddle.auto_archive_at is distinct from p_auto_archive_at then
    insert into public.huddle_messages (
      huddle_id,
      body,
      kind,
      activity_type,
      author_id,
      author_name
    )
    values (
      p_huddle_id,
      case
        when p_auto_archive_at is null then 'Auto-archive removed'
        when existing_huddle.auto_archive_at is null then format(
          'Auto-archive set for %s',
          to_char(p_auto_archive_at at time zone 'UTC', 'Mon FMDD, YYYY')
        )
        else format(
          'Auto-archive updated from %s to %s',
          to_char(existing_huddle.auto_archive_at at time zone 'UTC', 'Mon FMDD, YYYY'),
          to_char(p_auto_archive_at at time zone 'UTC', 'Mon FMDD, YYYY')
        )
      end,
      'system',
      'auto_archive_updated',
      auth.uid(),
      'System'
    );
  end if;

  insert into public.huddle_messages (
    huddle_id,
    body,
    kind,
    activity_type,
    author_id,
    author_name
  )
  select
    p_huddle_id,
    format(
      'Member added: %s',
      public.get_huddle_member_display_name(
        nullif(member.value ->> 'member_id', '')::uuid,
        nullif(member.value ->> 'member_tag', ''),
        nullif(member.value ->> 'member_phone_number', '')
      )
    ),
    'system',
    'member_added',
    auth.uid(),
    'System'
  from jsonb_array_elements(p_members) as member(value)
  where not exists (
    select 1
    from public.huddle_members existing_member
    where existing_member.huddle_id = p_huddle_id
      and existing_member.status = 'active'
      and coalesce(
        existing_member.member_id::text,
        existing_member.member_tag,
        existing_member.member_phone_number
      ) = coalesce(
        nullif(member.value ->> 'member_id', ''),
        nullif(member.value ->> 'member_tag', ''),
        nullif(member.value ->> 'member_phone_number', '')
      )
  );

  insert into public.huddle_messages (
    huddle_id,
    body,
    kind,
    activity_type,
    author_id,
    author_name
  )
  select
    p_huddle_id,
    format(
      'Member removed: %s',
      public.get_huddle_member_display_name(
        existing_member.member_id,
        existing_member.member_tag,
        existing_member.member_phone_number
      )
    ),
    'system',
    'member_removed',
    auth.uid(),
    'System'
  from public.huddle_members existing_member
  where existing_member.huddle_id = p_huddle_id
    and existing_member.status = 'active'
    and not exists (
      select 1
      from jsonb_array_elements(p_members) as member(value)
      where coalesce(
        nullif(member.value ->> 'member_id', ''),
        nullif(member.value ->> 'member_tag', ''),
        nullif(member.value ->> 'member_phone_number', '')
      ) = coalesce(
        existing_member.member_id::text,
        existing_member.member_tag,
        existing_member.member_phone_number
      )
    );

  update public.huddles as huddle
  set title = trim(p_title), auto_archive_at = p_auto_archive_at
  where huddle.id = p_huddle_id;

  update public.huddle_members existing_member
  set status = 'left', left_at = now()
  where existing_member.huddle_id = p_huddle_id
    and existing_member.status = 'active'
    and not exists (
      select 1
      from jsonb_array_elements(p_members) as member(value)
      where coalesce(
        nullif(member.value ->> 'member_id', ''),
        nullif(member.value ->> 'member_tag', ''),
        nullif(member.value ->> 'member_phone_number', '')
      ) = coalesce(
        existing_member.member_id::text,
        existing_member.member_tag,
        existing_member.member_phone_number
      )
    );

  update public.huddle_members existing_member
  set status = 'active', left_at = null
  where existing_member.huddle_id = p_huddle_id
    and existing_member.status = 'left'
    and exists (
      select 1
      from jsonb_array_elements(p_members) as member(value)
      where coalesce(
        nullif(member.value ->> 'member_id', ''),
        nullif(member.value ->> 'member_tag', ''),
        nullif(member.value ->> 'member_phone_number', '')
      ) = coalesce(
        existing_member.member_id::text,
        existing_member.member_tag,
        existing_member.member_phone_number
      )
    );

  insert into public.huddle_members (
    huddle_id,
    member_id,
    member_tag,
    member_phone_number
  )
  select
    p_huddle_id,
    nullif(member.value ->> 'member_id', '')::uuid,
    nullif(member.value ->> 'member_tag', ''),
    nullif(member.value ->> 'member_phone_number', '')
  from jsonb_array_elements(p_members) as member(value)
  where not exists (
    select 1
    from public.huddle_members existing_member
    where existing_member.huddle_id = p_huddle_id
      and coalesce(
        existing_member.member_id::text,
        existing_member.member_tag,
        existing_member.member_phone_number
      ) = coalesce(
        nullif(member.value ->> 'member_id', ''),
        nullif(member.value ->> 'member_tag', ''),
        nullif(member.value ->> 'member_phone_number', '')
      )
  )
  on conflict do nothing;

  return query
  select
    h.id,
    h.title,
    h.owner_id,
    h.created_at,
    h.auto_archive_at
  from public.huddles h
  where h.id = p_huddle_id;
end;
$$;

grant execute on function public.update_huddle(uuid, text, timestamptz, jsonb) to authenticated;

create or replace function public.leave_huddle(p_huddle_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_profile public.profiles;
begin
  if auth.uid() is null then
    raise exception 'An authenticated account is required.';
  end if;

  if not public.can_access_huddle(p_huddle_id) then
    raise exception 'You are not allowed to leave this huddle.';
  end if;

  select *
  into current_profile
  from public.profiles
  where id = auth.uid();

  update public.huddle_members membership
  set status = 'left', left_at = now()
  where membership.huddle_id = p_huddle_id
    and membership.status = 'active'
    and (
      membership.member_id = auth.uid()
      or (
        current_profile.tag <> ''
        and membership.member_tag = current_profile.tag
      )
      or (
        current_profile.phone_number <> ''
        and membership.member_phone_number = current_profile.phone_number
      )
    );

  if not found then
    raise exception 'Your huddle membership could not be found.';
  end if;

  insert into public.huddle_messages (
    huddle_id,
    body,
    kind,
    activity_type,
    author_id,
    author_name
  )
  values (
    p_huddle_id,
    format(
      'Member left: %s',
      public.get_huddle_member_display_name(
        auth.uid(),
        current_profile.tag,
        current_profile.phone_number
      )
    ),
    'system',
    'member_left',
    auth.uid(),
    'System'
  );
end;
$$;

grant execute on function public.leave_huddle(uuid) to authenticated;

-- Adding return columns changes the function's PostgreSQL row type.
drop function if exists public.create_huddle_message(uuid, text);

create or replace function public.create_huddle_message(
  p_huddle_id uuid,
  p_body text
)
returns table (
  id uuid,
  huddle_id uuid,
  body text,
  kind text,
  activity_type text,
  author_id uuid,
  author_name text,
  author_avatar_url text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_profile public.profiles;
  new_message_id uuid;
begin
  if auth.uid() is null then
    raise exception 'An authenticated account is required.';
  end if;

  if not public.can_access_huddle(p_huddle_id) then
    raise exception 'You are not allowed to send messages in this huddle.';
  end if;

  if coalesce(trim(p_body), '') = '' then
    raise exception 'Message is required.';
  end if;

  select *
  into current_profile
  from public.profiles profile
  where profile.id = auth.uid();

  if not found then
    raise exception 'A profile is required to send messages.';
  end if;

  if coalesce(
    nullif(current_profile.display_name, ''),
    nullif(current_profile.tag, ''),
    nullif(current_profile.phone_number, '')
  ) is null then
    raise exception 'Set a profile identity before sending messages.';
  end if;

  insert into public.huddle_messages as message (
    huddle_id,
    body,
    kind,
    author_id,
    author_name
  )
  values (
    p_huddle_id,
    trim(p_body),
    'user',
    auth.uid(),
    coalesce(
      nullif(current_profile.display_name, ''),
      nullif(current_profile.tag, ''),
      current_profile.phone_number
    )
  )
  returning message.id into new_message_id;

  return query
  select
    message.id,
    message.huddle_id,
    message.body,
    message.kind,
    message.activity_type,
    message.author_id,
    message.author_name,
    current_profile.avatar_url,
    message.created_at
  from public.huddle_messages message
  where message.id = new_message_id;
end;
$$;

grant execute on function public.create_huddle_message(uuid, text) to authenticated;

-- Adding return columns changes the function's PostgreSQL row type.
drop function if exists public.list_huddle_messages(uuid);

create or replace function public.list_huddle_messages(p_huddle_id uuid)
returns table (
  id uuid,
  huddle_id uuid,
  body text,
  kind text,
  activity_type text,
  author_id uuid,
  author_name text,
  author_avatar_url text,
  created_at timestamptz,
  is_unread boolean
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'An authenticated account is required.';
  end if;

  if not public.can_access_huddle(p_huddle_id) then
    raise exception 'You are not allowed to read this huddle.';
  end if;

  return query
  select
    message.id,
    message.huddle_id,
    message.body,
    message.kind,
    message.activity_type,
    message.author_id,
    message.author_name,
    nullif(author_profile.avatar_url, ''),
    message.created_at,
    (
      message.created_at > coalesce(read_state.last_read_at, '-infinity'::timestamptz)
      and message.author_id is distinct from auth.uid()
    )
  from public.huddle_messages message
  left join public.profiles author_profile on author_profile.id = message.author_id
  left join public.huddle_read_states read_state on (
    read_state.huddle_id = message.huddle_id
    and read_state.profile_id = auth.uid()
  )
  where message.huddle_id = p_huddle_id
  order by message.created_at, message.id;
end;
$$;

grant execute on function public.list_huddle_messages(uuid) to authenticated;

create or replace function public.mark_huddle_read(p_huddle_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'An authenticated account is required.';
  end if;

  if not public.can_access_huddle(p_huddle_id) then
    raise exception 'You are not allowed to read this huddle.';
  end if;

  insert into public.huddle_read_states as read_state (
    profile_id,
    huddle_id,
    last_read_at
  )
  values (auth.uid(), p_huddle_id, now())
  on conflict (profile_id, huddle_id) do update
  set last_read_at = greatest(read_state.last_read_at, excluded.last_read_at);
end;
$$;

grant execute on function public.mark_huddle_read(uuid) to authenticated;

alter table public.huddles enable row level security;
alter table public.huddle_members enable row level security;
alter table public.huddle_messages enable row level security;
alter table public.huddle_read_states enable row level security;

drop policy if exists "Members can read visible huddles" on public.huddles;
drop policy if exists "Authenticated users can create huddles" on public.huddles;
drop policy if exists "Members can update visible huddles" on public.huddles;
drop policy if exists "Members can delete visible huddles" on public.huddles;
drop policy if exists "Members can read visible huddle members" on public.huddle_members;
drop policy if exists "Huddle members can be added to visible huddles" on public.huddle_members;
drop policy if exists "Huddle members can be removed from visible huddles" on public.huddle_members;
drop policy if exists "Members can read visible huddle messages" on public.huddle_messages;
drop policy if exists "Members can create user messages" on public.huddle_messages;
drop policy if exists "Users can read their huddle read state" on public.huddle_read_states;
drop policy if exists "Users can create their huddle read state" on public.huddle_read_states;
drop policy if exists "Users can update their huddle read state" on public.huddle_read_states;

create policy "Members can read visible huddles"
  on public.huddles for select
  to authenticated
  using (public.can_access_huddle(id));

create policy "Authenticated users can create huddles"
  on public.huddles for insert
  to authenticated
  with check (auth.uid() = owner_id);

create policy "Members can update visible huddles"
  on public.huddles for update
  to authenticated
  using (public.can_access_huddle(id))
  with check (public.can_access_huddle(id));

create policy "Members can delete visible huddles"
  on public.huddles for delete
  to authenticated
  using (public.can_access_huddle(id));

create policy "Members can read visible huddle members"
  on public.huddle_members for select
  to authenticated
  using (public.can_access_huddle(huddle_id));

create policy "Huddle members can be added to visible huddles"
  on public.huddle_members for insert
  to authenticated
  with check (public.can_access_huddle(huddle_id));

create policy "Huddle members can be removed from visible huddles"
  on public.huddle_members for delete
  to authenticated
  using (public.can_access_huddle(huddle_id));

create policy "Members can read visible huddle messages"
  on public.huddle_messages for select
  to authenticated
  using (public.can_access_huddle(huddle_id));

create policy "Members can create user messages"
  on public.huddle_messages for insert
  to authenticated
  with check (
    public.can_access_huddle(huddle_id)
    and kind = 'user'
    and activity_type is null
    and author_id = auth.uid()
  );

create policy "Users can read their huddle read state"
  on public.huddle_read_states for select
  to authenticated
  using (profile_id = auth.uid());

create policy "Users can create their huddle read state"
  on public.huddle_read_states for insert
  to authenticated
  with check (profile_id = auth.uid() and public.can_access_huddle(huddle_id));

create policy "Users can update their huddle read state"
  on public.huddle_read_states for update
  to authenticated
  using (profile_id = auth.uid())
  with check (profile_id = auth.uid() and public.can_access_huddle(huddle_id));
